<?php
/**
 * Sets up ACF fields
 *
 * @since 0.0.2
 * @package WPHeadlessForms
 */

/**
 * Function to create ACF fields
 */
function wphf_create_fields() {
	if ( function_exists( 'acf_add_local_field_group' ) ) :

		acf_add_local_field_group(
			array(
				'key'                   => 'group_5cd0d6808dadc',
				'title'                 => 'Form Settings',
				'fields'                => array(
					array(
						'key'               => 'field_5cd0d68eccc93',
						'label'             => 'Fields',
						'name'              => 'fields',
						'type'              => 'flexible_content',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layouts'           => array(
							'layout_5cd0d6b3714ab' => array(
								'key'        => 'layout_5cd0d6b3714ab',
								'name'       => 'text',
								'label'      => 'Text',
								'display'    => 'block',
								'sub_fields' => array(
									array(
										'key'           => 'field_5cd0d6c6ccc94',
										'label'         => 'Name',
										'name'          => 'name',
										'type'          => 'text',
										'instructions'  => '',
										'required'      => 1,
										'conditional_logic' => 0,
										'wrapper'       => array(
											'width' => '50',
											'class' => '',
											'id'    => '',
										),
										'default_value' => '',
										'placeholder'   => '',
										'prepend'       => '',
										'append'        => '',
										'maxlength'     => '',
									),
									array(
										'key'           => 'field_5cd0d6dbccc95',
										'label'         => 'Label',
										'name'          => 'label',
										'type'          => 'text',
										'instructions'  => '',
										'required'      => 0,
										'conditional_logic' => 0,
										'wrapper'       => array(
											'width' => '50',
											'class' => '',
											'id'    => '',
										),
										'default_value' => '',
										'placeholder'   => '',
										'prepend'       => '',
										'append'        => '',
										'maxlength'     => '',
									),
									array(
										'key'           => 'field_5cd0ed11106dd',
										'label'         => 'Required',
										'name'          => 'required',
										'type'          => 'true_false',
										'instructions'  => '',
										'required'      => 0,
										'conditional_logic' => 0,
										'wrapper'       => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'message'       => '',
										'default_value' => 0,
										'ui'            => 0,
										'ui_on_text'    => '',
										'ui_off_text'   => '',
									),
								),
								'min'        => '',
								'max'        => '',
							),
							'layout_5cd0d6f6ccc96' => array(
								'key'        => 'layout_5cd0d6f6ccc96',
								'name'       => 'email',
								'label'      => 'Email',
								'display'    => 'block',
								'sub_fields' => array(
									array(
										'key'           => 'field_5cd0d70accc98',
										'label'         => 'Name',
										'name'          => 'name',
										'type'          => 'text',
										'instructions'  => '',
										'required'      => 1,
										'conditional_logic' => 0,
										'wrapper'       => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'default_value' => '',
										'placeholder'   => '',
										'prepend'       => '',
										'append'        => '',
										'maxlength'     => '',
									),
									array(
										'key'           => 'field_5cd0d70eccc99',
										'label'         => 'Label',
										'name'          => 'label',
										'type'          => 'text',
										'instructions'  => '',
										'required'      => 0,
										'conditional_logic' => 0,
										'wrapper'       => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'default_value' => '',
										'placeholder'   => '',
										'prepend'       => '',
										'append'        => '',
										'maxlength'     => '',
									),
									array(
										'key'           => 'field_5cd0edfc278cd',
										'label'         => 'Required',
										'name'          => 'required',
										'type'          => 'true_false',
										'instructions'  => '',
										'required'      => 0,
										'conditional_logic' => 0,
										'wrapper'       => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'message'       => '',
										'default_value' => 0,
										'ui'            => 0,
										'ui_on_text'    => '',
										'ui_off_text'   => '',
									),
									array(
										'key'           => 'field_5cd0ee0b278ce',
										'label'         => 'Send user confirmations to this address',
										'name'          => 'user_confirmations',
										'type'          => 'true_false',
										'instructions'  => '',
										'required'      => 0,
										'conditional_logic' => 0,
										'wrapper'       => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'message'       => '',
										'default_value' => 0,
										'ui'            => 0,
										'ui_on_text'    => '',
										'ui_off_text'   => '',
									),
								),
								'min'        => '',
								'max'        => '',
							),
							'layout_5cd0d718ccc9a' => array(
								'key'        => 'layout_5cd0d718ccc9a',
								'name'       => 'text_area',
								'label'      => 'Text Area',
								'display'    => 'row',
								'sub_fields' => array(
									array(
										'key'           => 'field_5cd0d71dccc9b',
										'label'         => 'Name',
										'name'          => 'name',
										'type'          => 'text',
										'instructions'  => '',
										'required'      => 1,
										'conditional_logic' => 0,
										'wrapper'       => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'default_value' => '',
										'placeholder'   => '',
										'prepend'       => '',
										'append'        => '',
										'maxlength'     => '',
									),
									array(
										'key'           => 'field_5cd0d731ccc9c',
										'label'         => 'Label',
										'name'          => 'label',
										'type'          => 'text',
										'instructions'  => '',
										'required'      => 0,
										'conditional_logic' => 0,
										'wrapper'       => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'default_value' => '',
										'placeholder'   => '',
										'prepend'       => '',
										'append'        => '',
										'maxlength'     => '',
									),
								),
								'min'        => '',
								'max'        => '',
							),
						),
						'button_label'      => 'Add Field',
						'min'               => '',
						'max'               => '',
					),
					array(
						'key'               => 'field_5cd0ed5b278cb',
						'label'             => 'Recipient',
						'name'              => 'recipient',
						'type'              => 'email',
						'instructions'      => 'Email address for contact form responses to be sent.',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'forms',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'seamless',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
			)
		);

	endif;
}
